### ISSUE TITLE
程序在 Windows11 23H2 版本上崩溃闪退

### ISSUE THREAD

**Issue by xieyiincuit** [huzgd/ezdml#1]
不打开dmj文档时可以正常使用，但打开文件途中就会出现闪退。

**Comment by xieyiincuit** [comment]
不仅仅是自定义的问题，程序提供的Demo文件打开也会闪退

**Comment by huzgd** [comment]
谢谢反馈，我自己只用WIN7和WIN10，我回头找个WIN11&nbsp;23H2&nbsp;看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huzgd/ezdml"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月6日(星期二) 上午9:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [huzgd/ezdml] 程序在 Windows11 23H2 版本上崩溃闪退 (Issue #1)





 
不仅仅是自定义的问题，程序提供的Demo文件打开也会闪退

**Comment by xieyiincuit** [comment]
感谢，这是系统的一些详细信息：
> Edition	        Windows 11 Pro
Version	        23H2
Installed on	‎2/‎6/‎2024
OS build	        22631.3007
Experience	Windows Feature Experience Pack 1000.22681.1000.0

**Comment by huzgd** [comment]
我找了个差不多的中文系统试了几下，暂时没重现出问题（我用的是EZDML for win64 v3.56），估计还要再找找规律
![image](https://github.com/huzgd/ezdml/assets/23415733/8a746f56-9b5e-4715-9b03-287eea2e3d61)

**Comment by xieyiincuit** [comment]
我用的是英文版本的，并且可能没有装默认的中文语言补充包，难道是这个依赖的问题？

**Comment by huzgd** [comment]
理论上不影响，EZDML本来就是英文版基础上加的中文支持。我这边没人用英文版，回头看看能否换台机器再试试



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huzgd/ezdml"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月18日(星期天) 上午9:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huzgd/ezdml] 程序在 Windows11 23H2 版本上崩溃闪退 (Issue #1)





 
我用的是英文版本的，并且可能没有装默认的中文语言补充包，难道是这个依赖的问题？

**Comment by xieyiincuit** [comment]
![image](https://github.com/huzgd/ezdml/assets/57696015/3cb2f74d-c07d-45ae-8554-57618962302b)
进行了如下的设置，程序目前可以正常运行了。
